version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "11451:5000"
    environment:
      - FLASK_ENV=development
      - DB_USER=root
      - DB_PASSWORD=Tt102938!
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=ocean_monitor
    depends_on:
      db: 
        condition: service_healthy
    volumes:
      - ./server:/app
    restart: unless-stopped # Flask's hot reloading will stop it once error occurs


  client:
    build: ./client
    ports:
      - "19198:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_BASE_URL=http://127.0.0.1:11451
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Tt102938!
      MYSQL_DATABASE: ocean_monitor
      # MYSQL_USER: root
      # MYSQL_PASSWORD: Tt102938!
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  db_data:
